### ISSUE TITLE
[Bug] Can not format code inline

### ISSUE THREAD

**Issue by TungNguyen-C4U** [hunghg255/reactjs-tiptap-editor#133]
Code format text can not stay inline, can you please update this?

![Screenshot_20250103_080739_DataDude.jpg](https://github.com/user-attachments/assets/631c03cc-2710-4c49-b4b9-b158ebced2ac)

**Comment by hunghg255** [comment]
@TungNguyen-C4U I think this related to your style 
![Screenshot 2025-01-03 at 08 41 08](https://github.com/user-attachments/assets/8bc804b7-70c2-4e7c-9ff4-77aa52a0f870)

I want to try

```css
p code {
   display: inline;
}

pre code {
   display: block;
}
```
